name: flutter_news_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bookmarks:
    path: packages/features/bookmarks
  component_library:
    path: packages/component_library
  cupertino_icons: ^1.0.2
  domain_models:
    path: packages/domain_models
  flutter:
    sdk: flutter
  key_value_storage:
    path: packages/key_value_storage
  news_api:
    path: packages/news_api
  news_detail:
    path: packages/features/news_detail
  news_list:
    path: packages/features/news_list
  news_repository:
    path: packages/news_repository
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
