name: key_value_storage
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  equatable: ^2.0.5
  hive: ^2.2.3
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^4.0.0+1
