name: news_repository
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  domain_models:
    path: ../domain_models
  equatable: ^2.0.5
  key_value_storage:
    path: ../key_value_storage
  news_api:
    path: ../news_api
  

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0+1
