name: news_detail
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^5.7.2+3
  news_repository:
    path: ../../news_repository
  share_plus: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter: