name: settings
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  domain_models:
    path: ../../domain_models
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  rxdart: ^0.27.7
  settings_repository:
    path: ../../settings_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
